<?php

namespace AppBundle\Repository;

/**
 * Demande_CreditRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Demande_CreditRepository extends \Doctrine\ORM\EntityRepository
{
}
