<?php

namespace AppBundle\Repository;

/**
 * Detail_pièce_jointRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Detail_pièce_jointRepository extends \Doctrine\ORM\EntityRepository
{
}
