<?php

namespace AppBundle\Repository;

/**
 * Piece_jointRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Piece_jointRepository extends \Doctrine\ORM\EntityRepository
{
}
