sim_credit_homepage:
    path:     /
    defaults: { _controller: SimCreditBundle:DemandeCredit:new }

sim_credit_simulation:
    path:     /simulation
    defaults: { _controller: SimCreditBundle:DemandeCredit:new }
